services:
  web-api:
    build: .
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    container_name: clinical_api_service
    ports:
      - "8000:8000"
    environment:
      - EVAL_ENGINE=${EVAL_ENGINE}
      - EXTRACT_ENGINE=${EXTRACT_ENGINE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_FOR_EXTRACTION=${GEMINI_MODEL_FOR_EXTRACTION}
      - GEMINI_MODEL_FOR_EVALUATION=${GEMINI_MODEL_FOR_EVALUATION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_FOR_EXTRACTION=${OPENAI_MODEL_FOR_EXTRACTION}
      - OPENAI_MODEL_FOR_EVALUATION=${OPENAI_MODEL_FOR_EVALUATION}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - LLAMA_MODEL_FOR_EXTRACTION=${LLAMA_MODEL_FOR_EXTRACTION}
      - LLAMA_MODEL_FOR_EVALUATION=${LLAMA_MODEL_FOR_EVALUATION}
      - API_KEY=${API_KEY}
      - UV_LINK_MODE=copy
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/clinical_pipeline
    depends_on:
      - ollama-service
      - postgres
    volumes:
      - .:/app
      - venv-data:/app/.venv
    networks:
      - pipeline-network

  ollama-service:
    image: ollama/ollama:latest
    container_name: local_ollama_engine
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - pipeline-network
    attach: false

  postgres:
    image: postgres:16-alpine
    container_name: clinical_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinical_pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline-network
    attach: false

volumes:
  ollama_storage:
    name: ollama_storage
  venv-data:
  postgres_data:

networks:
  pipeline-network:
    driver: bridge
